@echo off
echo [SYSTEM] Mematikan bot lama...
pm2 delete MyTradingBot >nul 2>&1
echo [SYSTEM] Mengambil kode terbaru dari GitHub...
git pull
echo [SYSTEM] Menjalankan bot baru...
pm2 start python --name "MyTradingBot" -- main.py
echo [SYSTEM] Selesai! Menampilkan log...
timeout /t 2
pm2 logs MyTradingBot --lines 20
